site_name: My Blog
repo_name: padhysai
repo_url: https://github.com/padhysai/padhysai.github.io
theme:
  name: material
  logo: https://img.icons8.com/ios-filled/72/circled-s.png
  favicon: https://img.icons8.com/color/2x/s.png
  palette:
    scheme: preference
    primary: purple
    accent: indigo
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/padhysai
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/saiprasadpadhy/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sai_prasad006/
      disqus: your-shortname

use_directory_urls: false
copyright: |
  &copy; 2020 <a href="https://github.com/padhysai"  target="_blank" rel="noopener">Sai Prasad Padhy</a>

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.arithmatex
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark

markdown_extensions:
  - codehilite